version: '3'
services:
  game_api:
    image: emiln17/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - my_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: my_database_container
      POSTGRES_DB: game_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
  my_database_container:
    image: postgres
    environment:
      POSTGRES_DB: game_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
  game_client:
    image: emiln17/game_client:${GIT_COMMIT}
    ports:
    - '4000:4000'
    depends_on:
    - game_api
    environment:
      PORT: 4000
      API_PORT: 3000
      API_URL: ${API_URL}
  my_datadog_container:
    image: datadog/agent:latest
    environment:
      DD_API_KEY: '1a4f8a200531e718712202da7a0282fe'
      DD_SITE: 'datadoghq.eu'
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: 'true'
      DD_TAGS: ${ENVIRONMENT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/mounts:/host/proc/mounts:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro